app:
  build: .
  ports:
    - "3000:3000"
  # volumes:
  #   - .:/usr/src/app
  links:
    - db:db
  restart: always
  environment:
    # RAILS_ENV: production
    # SECRET_KEY_BASE: need_security
    DATABASE_URL: postgres://postgres@db:5432

db:
  image: postgres
  ports:
    - "5432:5432"
  # volumes:
    # - postgresql:/var/lib/postgresql
  restart: always
