# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 775f6940b8baf895a4d304f09ff9d21c9c89f74440fd9f5608b847bf298c8395d8b96eaf3d7966c45cf9a0a690683aedb9f632033897a5f021ee2d2707005c5d
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY_DEV'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET_DEV'] %>
  github_client_id: <%= ENV['GITHUB_CLIENT_ID_DEV'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET_DEV'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID_DEV'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET_DEV'] %>

test:
  secret_key_base: 98af1b396e48e1f1c6309ff7f994d63efee8a17595666f8e7893e1b85337b036c681f707004c54d34bd5a39879f7c9b2461975f3c056ec94b5bc516577cf131a
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY_TEST'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET_TEST'] %>
  github_client_id: <%= ENV['GITHUB_CLIENT_ID_TEST'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET_TEST'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID_TEST'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET_TEST'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
  github_client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
